# Generated by Django 3.2.6 on 2021-08-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210825_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
