# Generated by Django 3.2.6 on 2021-08-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210827_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='auctions.Item'),
        ),
    ]
